#!/bin/bash

OCTANIS1_ENERGIA='~/Desktop/Octanis/Octanis1-Energia'


ln -s $OCTANIS1_ENERGIA/hardware/msp430/libraries /Applications/Energia.app/Contents/Resources/Java/hardware/msp430/
ln -s $OCTANIS1_ENERGIA/hardware/msp430/cores /Applications/Energia.app/Contents/Resources/Java/hardware/msp430/ 
ln -s $OCTANIS1_ENERGIA/hardware/msp430/boards.txt /Applications/Energia.app/Contents/Resources/Java/hardware/msp430  
ln -s $OCTANIS1_ENERGIA/hardware/msp430/variants/octanis1_v0_1 /Applications/Energia.app/Contents/Resources/Java/hardware/msp430/variants
ln -s $OCTANIS1_ENERGIA/sandbox /Applications/Energia.app/Contents/Resources/Java/examples 

